package com.acme.banking.api.dto;

import com.acme.banking.core.model.Account;
import jakarta.annotation.Generated;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record AccountResponse(Long id, String accountNumber, BigDecimal balanceAmount,
        String balanceCurrency, Long customerId, boolean active) {
    public static AccountResponse from(Account source) {
        return new AccountResponse(
                        source.getId() != null ? source.getId().value() : null,
                        source.getAccountNumber(),
                        source.getBalance() != null ? source.getBalance().amount() : null,
                        source.getBalance() != null ? source.getBalance().currency() : null,
                        source.getCustomerId() != null ? source.getCustomerId().value() : null,
                        source.isActive());
    }
}
