package com.acme.banking.api.dto;

import jakarta.annotation.Generated;
import jakarta.validation.constraints.NotNull;
import java.lang.Long;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record BlockCardRequest(@NotNull Long cardId) {
}
