package com.acme.banking.api.dto;

import com.acme.banking.core.model.Card;
import jakarta.annotation.Generated;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;
import java.time.LocalDate;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record CardResponse(Long id, String cardNumber, LocalDate expiryDate, String cvv,
        Long accountId, BigDecimal dailyLimitAmount, String dailyLimitCurrency) {
    public static CardResponse from(Card source) {
        return new CardResponse(
                        source.getId() != null ? source.getId().value() : null,
                        source.getCardNumber(),
                        source.getExpiryDate(),
                        source.getCvv(),
                        source.getAccountId() != null ? source.getAccountId().value() : null,
                        source.getDailyLimit() != null ? source.getDailyLimit().amount() : null,
                        source.getDailyLimit() != null ? source.getDailyLimit().currency() : null);
    }
}
