package com.acme.banking.api.dto;

import jakarta.annotation.Generated;
import jakarta.validation.constraints.NotBlank;
import java.lang.String;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record CreateCustomerRequest(@NotBlank String firstName, @NotBlank String lastName,
        @NotBlank String email, @NotBlank String phone) {
}
