package com.acme.banking.api.dto;

import com.acme.banking.core.model.Customer;
import jakarta.annotation.Generated;
import java.lang.Long;
import java.lang.String;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record CustomerResponse(Long id, String firstName, String lastName, String email,
        String phone, String addressStreet, String addressCity, String addressZipCode,
        String addressCountry) {
    public static CustomerResponse from(Customer source) {
        return new CustomerResponse(
                        source.getId() != null ? source.getId().value() : null,
                        source.getFirstName(),
                        source.getLastName(),
                        source.getEmail() != null ? source.getEmail().value() : null,
                        source.getPhone(),
                        source.getAddress() != null ? source.getAddress().street() : null,
                        source.getAddress() != null ? source.getAddress().city() : null,
                        source.getAddress() != null ? source.getAddress().zipCode() : null,
                        source.getAddress() != null ? source.getAddress().country() : null);
    }
}
