package com.acme.banking.api.dto;

import com.acme.banking.core.model.Money;
import jakarta.annotation.Generated;
import java.lang.String;
import java.math.BigDecimal;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record MoneyResponse(BigDecimal amount, String currency) {
    public static MoneyResponse from(Money source) {
        return new MoneyResponse(
                        source.amount(),
                        source.currency());
    }
}
