package com.acme.banking.api.dto;

import com.acme.banking.core.model.TransactionType;
import jakarta.annotation.Generated;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record RecordTransactionRequest(@NotNull Long accountId, @NotNull BigDecimal amount,
        @NotBlank String currency, @NotNull TransactionType type, @NotBlank String description,
        @NotBlank String reference) {
}
