package com.acme.banking.api.dto;

import com.acme.banking.core.model.Transfer;
import jakarta.annotation.Generated;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record TransferResponse(Long id, Long sourceAccountId, Long targetAccountId,
        BigDecimal amountAmount, String amountCurrency, String reason) {
    public static TransferResponse from(Transfer source) {
        return new TransferResponse(
                        source.getId() != null ? source.getId().value() : null,
                        source.getSourceAccountId() != null ? source.getSourceAccountId().value() : null,
                        source.getTargetAccountId() != null ? source.getTargetAccountId().value() : null,
                        source.getAmount() != null ? source.getAmount().amount() : null,
                        source.getAmount() != null ? source.getAmount().currency() : null,
                        source.getReason());
    }
}
