package com.acme.banking.api.dto;

import com.acme.banking.core.model.Transaction;
import jakarta.annotation.Generated;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
public record TransactionResponse(Long id, BigDecimal amountAmount, String amountCurrency,
        String description, String reference, Long accountId) {
    public static TransactionResponse from(Transaction source) {
        return new TransactionResponse(
                        source.getId() != null ? source.getId().value() : null,
                        source.getAmount() != null ? source.getAmount().amount() : null,
                        source.getAmount() != null ? source.getAmount().currency() : null,
                        source.getDescription(),
                        source.getReference(),
                        source.getAccountId() != null ? source.getAccountId().value() : null);
    }
}
