package com.acme.banking.api.controller;

import com.acme.banking.api.dto.AccountResponse;
import com.acme.banking.api.dto.CloseAccountRequest;
import com.acme.banking.api.dto.DepositRequest;
import com.acme.banking.api.dto.MoneyResponse;
import com.acme.banking.api.dto.OpenAccountRequest;
import com.acme.banking.api.dto.WithdrawRequest;
import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.CustomerId;
import com.acme.banking.core.model.Money;
import com.acme.banking.core.port.in.AccountUseCases;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
@RestController
@RequestMapping("/api/accounts")
@Tag(
        name = "Accounts",
        description = "Account management operations"
)
public class AccountController {
    private final AccountUseCases accountUseCases;

    public AccountController(AccountUseCases accountUseCases) {
        this.accountUseCases = accountUseCases;
    }

    @Operation(
            summary = "Close account"
    )
    @ApiResponse(
            responseCode = "204",
            description = "Close account completed successfully"
    )
    @DeleteMapping("/{id}")
    public ResponseEntity<Object> closeAccount(@PathVariable Long id,
            @Valid @RequestBody CloseAccountRequest request) {
        accountUseCases.closeAccount(
                        new AccountId(id));
        return ResponseEntity.noContent().build();
    }

    @Operation(
            summary = "Deposit"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Deposit completed successfully"
    )
    @PostMapping("/{id}/deposit")
    public ResponseEntity<Object> deposit(@PathVariable Long id,
            @Valid @RequestBody DepositRequest request) {
        var result = accountUseCases.deposit(
                        new AccountId(id),
                        new Money(request.amount(), request.currency()));
        return ResponseEntity.ok(AccountResponse.from(result));
    }

    @Operation(
            summary = "Get account"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Get account completed successfully"
    )
    @GetMapping("/{id}")
    public ResponseEntity<Object> getAccount(@PathVariable Long id) {
        var result = accountUseCases.getAccount(
                        new AccountId(id));
        return ResponseEntity.ok(AccountResponse.from(result));
    }

    @Operation(
            summary = "Get account by number"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Get account by number completed successfully"
    )
    @GetMapping("/by-number/{accountNumber}")
    public ResponseEntity<Object> getAccountByNumber(@PathVariable String accountNumber) {
        var result = accountUseCases.getAccountByNumber(
                        accountNumber);
        return ResponseEntity.ok(AccountResponse.from(result));
    }

    @Operation(
            summary = "Get accounts by customer"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Get accounts by customer completed successfully"
    )
    @GetMapping("/by-customer/{customerId}")
    public ResponseEntity<Object> getAccountsByCustomer(@PathVariable Long customerId) {
        var result = accountUseCases.getAccountsByCustomer(
                        new CustomerId(customerId));
        return ResponseEntity.ok(result);
    }

    @Operation(
            summary = "Get balance"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Get balance completed successfully"
    )
    @GetMapping("/get-balance/{id}")
    public ResponseEntity<Object> getBalance(@PathVariable Long id) {
        var result = accountUseCases.getBalance(
                        new AccountId(id));
        return ResponseEntity.ok(MoneyResponse.from(result));
    }

    @Operation(
            summary = "Open account"
    )
    @ApiResponse(
            responseCode = "201",
            description = "Open account completed successfully"
    )
    @PostMapping
    public ResponseEntity<Object> openAccount(@Valid @RequestBody OpenAccountRequest request) {
        var result = accountUseCases.openAccount(
                        new CustomerId(request.customerId()),
                        request.type(),
                        request.accountNumber());
        return ResponseEntity.ok(AccountResponse.from(result));
    }

    @Operation(
            summary = "Withdraw"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Withdraw completed successfully"
    )
    @PostMapping("/{id}/withdraw")
    public ResponseEntity<Object> withdraw(@PathVariable Long id,
            @Valid @RequestBody WithdrawRequest request) {
        var result = accountUseCases.withdraw(
                        new AccountId(id),
                        new Money(request.amount(), request.currency()));
        return ResponseEntity.ok(AccountResponse.from(result));
    }
}
