package com.acme.banking.api.controller;

import com.acme.banking.api.dto.RecordTransactionRequest;
import com.acme.banking.api.dto.TransactionResponse;
import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.Money;
import com.acme.banking.core.model.TransactionType;
import com.acme.banking.core.port.in.TransactionUseCases;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import java.lang.Long;
import java.lang.Object;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@Generated(
        value = "io.hexaglue.plugin.rest",
        comments = "Generated by HexaGlue REST Plugin"
)
@RestController
@RequestMapping("/api/transactions")
@Tag(
        name = "Transactions",
        description = "Transaction management operations"
)
public class TransactionController {
    private final TransactionUseCases transactionUseCases;

    public TransactionController(TransactionUseCases transactionUseCases) {
        this.transactionUseCases = transactionUseCases;
    }

    @Operation(
            summary = "Get history"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Get history completed successfully"
    )
    @GetMapping("/get-history")
    public ResponseEntity<Object> getHistory(@RequestParam(required = true) Long accountId) {
        var result = transactionUseCases.getHistory(
                        new AccountId(accountId));
        return ResponseEntity.ok(result);
    }

    @Operation(
            summary = "Get statement"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Get statement completed successfully"
    )
    @GetMapping("/get-statement")
    public ResponseEntity<Object> getStatement(@RequestParam(required = true) Long accountId,
            @RequestParam(required = true) TransactionType type) {
        var result = transactionUseCases.getStatement(
                        new AccountId(accountId),
                        type);
        return ResponseEntity.ok(result);
    }

    @Operation(
            summary = "Record transaction"
    )
    @ApiResponse(
            responseCode = "200",
            description = "Record transaction completed successfully"
    )
    @PostMapping("/record-transaction")
    public ResponseEntity<Object> recordTransaction(
            @Valid @RequestBody RecordTransactionRequest request) {
        var result = transactionUseCases.recordTransaction(
                        new AccountId(request.accountId()),
                        new Money(request.amount(), request.currency()),
                        request.type(),
                        request.description(),
                        request.reference());
        return ResponseEntity.ok(TransactionResponse.from(result));
    }
}
