package com.acme.banking.infrastructure.persistence;

import java.lang.Long;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link AccountJpaEntity}.
 *
 * <p>This interface provides CRUD operations for AccountJpaEntity entities.
 * Spring Data JPA automatically implements standard methods:
 * <ul>
 *   <li>{@code save(entity)}</li>
 *   <li>{@code findById(id)}</li>
 *   <li>{@code findAll()}</li>
 *   <li>{@code delete(entity)}</li>
 *   <li>{@code count()}</li>
 * </ul>
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-09T09:29:04.825610Z"
)
@Repository
public interface AccountJpaRepository extends JpaRepository<AccountJpaEntity, Long> {
    Optional<AccountJpaEntity> findByAccountNumber(String accountNumber);

    List<AccountJpaEntity> findByActiveTrue();

    List<AccountJpaEntity> findByCustomerId(Long customerId);

    Optional<AccountJpaEntity> findById(Long id);
}
