package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.Account;
import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.CustomerId;
import com.acme.banking.core.port.out.AccountRepository;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
        value = "io.hexaglue.plugin.jpa.JpaPlugin",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-05T14:47:09.273365Z"
)
@Component
public class AccountRepositoryAdapter implements AccountRepository {
    private final AccountJpaRepository repository;

    private final AccountMapper mapper;

    public AccountRepositoryAdapter(AccountJpaRepository repository, AccountMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @Override
    public List<Account> findAll() {
        return repository.findAll().stream().map(mapper::toDomain).toList();
    }

    @Override
    public Optional<Account> findByAccountNumber(String accountNumber) {
        return repository.findByAccountNumber(accountNumber).map(mapper::toDomain);
    }

    @Override
    public List<Account> findByActiveTrue() {
        return repository.findByActiveTrue().stream().map(mapper::toDomain).toList();
    }

    @Override
    public List<Account> findByCustomerId(CustomerId customerId) {
        return repository.findByCustomerId(customerId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public Optional<Account> findById(AccountId id) {
        return repository.findById(mapper.map(id)).map(mapper::toDomain);
    }

    @Override
    public Account save(Account account) {
        var entity = mapper.toEntity(account);
        var saved = repository.save(entity);
        return mapper.toDomain(saved);
    }
}
