package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.AccountType;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.lang.Long;
import java.lang.String;
import javax.annotation.processing.Generated;

@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0",
        date = "2026-03-09T10:32:36.081072Z"
)
@Entity
@Table(
        name = "account"
)
public class AccountJpaEntity {
    @Id
    @Column(
            name = "id",
            nullable = false
    )
    @GeneratedValue(
            strategy = GenerationType.IDENTITY
    )
    private Long id;

    @Column(
            name = "account_number"
    )
    private String accountNumber;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "type"
    )
    private AccountType type;

    @Column(
            name = "customer_id"
    )
    private Long customerId;

    @Column(
            name = "active"
    )
    private boolean active;

    @Embedded
    private MoneyEmbeddable balance;

    public AccountJpaEntity() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public AccountType getType() {
        return type;
    }

    public void setType(AccountType type) {
        this.type = type;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public MoneyEmbeddable getBalance() {
        return balance;
    }

    public void setBalance(MoneyEmbeddable balance) {
        this.balance = balance;
    }
}
