package com.acme.banking.infrastructure.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.lang.String;
import javax.annotation.processing.Generated;

@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-05T14:47:09.251618Z"
)
@Embeddable
public class AddressEmbeddable {
    @Column(
            name = "street"
    )
    private String street;

    @Column(
            name = "city"
    )
    private String city;

    @Column(
            name = "zip_code"
    )
    private String zipCode;

    @Column(
            name = "country"
    )
    private String country;

    public AddressEmbeddable() {
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }
}
