package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.Address;
import com.acme.banking.core.model.Beneficiary;
import com.acme.banking.core.model.BeneficiaryId;
import com.acme.banking.core.model.CustomerId;
import com.acme.banking.core.model.Iban;
import com.acme.banking.core.model.Money;
import java.lang.Long;
import java.lang.String;
import javax.annotation.processing.Generated;
import org.mapstruct.CollectionMappingStrategy;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * MapStruct mapper for converting between {@link com.acme.banking.core.model.Beneficiary} domain objects and {@link com.acme.banking.infrastructure.persistence.BeneficiaryJpaEntity} entities.
 *
 * <p>This interface provides bidirectional mapping:
 * <ul>
 *   <li>{@code toEntity()} - converts domain to JPA entity</li>
 *   <li>{@code toDomain()} - converts JPA entity to domain</li>
 * </ul>
 *
 * <p>MapStruct generates the implementation at compile time, ensuring type safety
 * and optimal performance without runtime reflection.
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:28:52.468861Z"
)
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED
)
public interface BeneficiaryMapper {
    /**
     * Converts a domain object to a JPA entity.
     *
     * @param domain the domain object to convert
     * @return the corresponding JPA entity
     */
    BeneficiaryJpaEntity toEntity(Beneficiary domain);

    /**
     * Converts a JPA entity to a domain object using the {@code reconstitute()} factory method.
     *
     * @param entity the JPA entity to convert
     * @return the corresponding domain object, or null if entity is null
     */
    default Beneficiary toDomain(BeneficiaryJpaEntity entity) {
        if (entity == null) {
            return null;
        }
        return Beneficiary.reconstitute(
                    map(entity.getId()),
                    mapToCustomerId(entity.getCustomerId()),
                    entity.getName(),
                    mapToIban(entity.getIban()),
                    entity.getBic());
    }

    /**
     * Unwraps {@link com.acme.banking.core.model.BeneficiaryId} to {@link java.lang.Long}.
     *
     * @param id the wrapped identity
     * @return the unwrapped value, or null if input is null
     */
    default Long map(BeneficiaryId id) {
        return id != null ? id.value() : null;
    }

    /**
     * Wraps {@link java.lang.Long} into {@link com.acme.banking.core.model.BeneficiaryId}.
     *
     * @param id the unwrapped value
     * @return the wrapped identity, or null if input is null
     */
    default BeneficiaryId map(Long id) {
        return id != null ? new BeneficiaryId(id) : null;
    }

    /**
     * Unwraps {@link Iban} to {@link java.lang.String}.
     *
     * @param vo the Value Object to unwrap
     * @return the underlying value, or null if input is null
     */
    default String map(Iban vo) {
        return vo != null ? vo.value() : null;
    }

    /**
     * Wraps {@link java.lang.String} into {@link Iban}.
     *
     * @param value the primitive value to wrap
     * @return the Value Object, or null if input is null
     */
    default Iban mapToIban(String value) {
        return value != null ? new Iban(value) : null;
    }

    /**
     * Unwraps {@link CustomerId} to {@link java.lang.Long}.
     *
     * @param vo the Value Object to unwrap
     * @return the underlying value, or null if input is null
     */
    default Long map(CustomerId vo) {
        return vo != null ? vo.value() : null;
    }

    /**
     * Wraps {@link java.lang.Long} into {@link CustomerId}.
     *
     * @param value the primitive value to wrap
     * @return the Value Object, or null if input is null
     */
    default CustomerId mapToCustomerId(Long value) {
        return value != null ? new CustomerId(value) : null;
    }

    /**
     * Converts {@link Money} domain object to {@link MoneyEmbeddable} JPA embeddable.
     *
     * @param domain the domain VALUE_OBJECT to convert
     * @return the corresponding JPA embeddable
     */
    MoneyEmbeddable toEmbeddable(Money domain);

    /**
     * Converts {@link MoneyEmbeddable} JPA embeddable to {@link Money} domain object.
     *
     * @param embeddable the JPA embeddable to convert
     * @return the corresponding domain VALUE_OBJECT
     */
    Money toDomain(MoneyEmbeddable embeddable);

    /**
     * Converts {@link Address} domain object to {@link AddressEmbeddable} JPA embeddable.
     *
     * @param domain the domain VALUE_OBJECT to convert
     * @return the corresponding JPA embeddable
     */
    AddressEmbeddable toEmbeddable(Address domain);

    /**
     * Converts {@link AddressEmbeddable} JPA embeddable to {@link Address} domain object.
     *
     * @param embeddable the JPA embeddable to convert
     * @return the corresponding domain VALUE_OBJECT
     */
    Address toDomain(AddressEmbeddable embeddable);
}
