package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.Beneficiary;
import com.acme.banking.core.model.CustomerId;
import com.acme.banking.core.port.out.BeneficiaryRepository;
import java.lang.Override;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
        value = "io.hexaglue.plugin.jpa.JpaPlugin",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:30:55.828739Z"
)
@Component
public class BeneficiaryRepositoryAdapter implements BeneficiaryRepository {
    private final BeneficiaryJpaRepository repository;

    private final BeneficiaryMapper mapper;

    public BeneficiaryRepositoryAdapter(BeneficiaryJpaRepository repository,
            BeneficiaryMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @Override
    public List<Beneficiary> findByCustomerId(CustomerId customerId) {
        return repository.findByCustomerId(customerId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public Beneficiary save(Beneficiary beneficiary) {
        var entity = mapper.toEntity(beneficiary);
        var saved = repository.save(entity);
        return mapper.toDomain(saved);
    }
}
