package com.acme.banking.infrastructure.persistence;

import java.lang.Long;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link BeneficiaryJpaEntity}.
 *
 * <p>This interface provides CRUD operations for BeneficiaryJpaEntity entities.
 * Spring Data JPA automatically implements standard methods:
 * <ul>
 *   <li>{@code save(entity)}</li>
 *   <li>{@code findById(id)}</li>
 *   <li>{@code findAll()}</li>
 *   <li>{@code delete(entity)}</li>
 *   <li>{@code count()}</li>
 * </ul>
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:28:52.468419Z"
)
@Repository
public interface BeneficiaryJpaRepository extends JpaRepository<BeneficiaryJpaEntity, Long> {
    List<BeneficiaryJpaEntity> findByCustomerId(Long customerId);
}
