package com.acme.banking.infrastructure.persistence;

import java.lang.Long;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link CardJpaEntity}.
 *
 * <p>This interface provides CRUD operations for CardJpaEntity entities.
 * Spring Data JPA automatically implements standard methods:
 * <ul>
 *   <li>{@code save(entity)}</li>
 *   <li>{@code findById(id)}</li>
 *   <li>{@code findAll()}</li>
 *   <li>{@code delete(entity)}</li>
 *   <li>{@code count()}</li>
 * </ul>
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:28:52.470570Z"
)
@Repository
public interface CardJpaRepository extends JpaRepository<CardJpaEntity, Long> {
    List<CardJpaEntity> findByAccountId(Long accountId);

    Optional<CardJpaEntity> findByCardNumber(String cardNumber);

    Optional<CardJpaEntity> findById(Long id);
}
