package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.CardStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.lang.Long;
import java.lang.String;
import java.time.LocalDate;
import javax.annotation.processing.Generated;

@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-09T09:29:04.831747Z"
)
@Entity
@Table(
        name = "card"
)
public class CardJpaEntity {
    @Id
    @Column(
            name = "id",
            nullable = false
    )
    @GeneratedValue(
            strategy = GenerationType.IDENTITY
    )
    private Long id;

    @Column(
            name = "card_number"
    )
    private String cardNumber;

    @Column(
            name = "expiry_date"
    )
    private LocalDate expiryDate;

    @Column(
            name = "cvv"
    )
    private String cvv;

    @Column(
            name = "account_id"
    )
    private Long accountId;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "status"
    )
    private CardStatus status;

    @Embedded
    private MoneyEmbeddable dailyLimit;

    public CardJpaEntity() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    public String getCvv() {
        return cvv;
    }

    public void setCvv(String cvv) {
        this.cvv = cvv;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public CardStatus getStatus() {
        return status;
    }

    public void setStatus(CardStatus status) {
        this.status = status;
    }

    public MoneyEmbeddable getDailyLimit() {
        return dailyLimit;
    }

    public void setDailyLimit(MoneyEmbeddable dailyLimit) {
        this.dailyLimit = dailyLimit;
    }
}
