package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.Card;
import com.acme.banking.core.model.CardId;
import com.acme.banking.core.port.out.CardRepository;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
        value = "io.hexaglue.plugin.jpa.JpaPlugin",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:30:55.829134Z"
)
@Component
public class CardRepositoryAdapter implements CardRepository {
    private final CardJpaRepository repository;

    private final CardMapper mapper;

    public CardRepositoryAdapter(CardJpaRepository repository, CardMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @Override
    public List<Card> findByAccountId(AccountId accountId) {
        return repository.findByAccountId(accountId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public Optional<Card> findByCardNumber(String cardNumber) {
        return repository.findByCardNumber(cardNumber).map(mapper::toDomain);
    }

    @Override
    public Optional<Card> findById(CardId id) {
        return repository.findById(mapper.map(id)).map(mapper::toDomain);
    }

    @Override
    public Card save(Card card) {
        var entity = mapper.toEntity(card);
        var saved = repository.save(entity);
        return mapper.toDomain(saved);
    }
}
