package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.Customer;
import com.acme.banking.core.model.CustomerId;
import com.acme.banking.core.model.Email;
import com.acme.banking.core.port.out.CustomerRepository;
import java.lang.Override;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
        value = "io.hexaglue.plugin.jpa.JpaPlugin",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-09T09:29:04.844047Z"
)
@Component
public class CustomerRepositoryAdapter implements CustomerRepository {
    private final CustomerJpaRepository repository;

    private final CustomerMapper mapper;

    public CustomerRepositoryAdapter(CustomerJpaRepository repository, CustomerMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @Override
    public boolean existsByEmail(Email email) {
        return repository.existsByEmail(mapper.map(email));
    }

    @Override
    public Optional<Customer> findByEmail(Email email) {
        return repository.findByEmail(mapper.map(email)).map(mapper::toDomain);
    }

    @Override
    public Optional<Customer> findById(CustomerId id) {
        return repository.findById(mapper.map(id)).map(mapper::toDomain);
    }

    @Override
    public Customer save(Customer customer) {
        var entity = mapper.toEntity(customer);
        var saved = repository.save(entity);
        return mapper.toDomain(saved);
    }
}
