package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.Address;
import com.acme.banking.core.model.Customer;
import com.acme.banking.core.model.CustomerId;
import com.acme.banking.core.model.Email;
import com.acme.banking.core.model.Money;
import java.lang.Long;
import java.lang.String;
import javax.annotation.processing.Generated;
import org.mapstruct.CollectionMappingStrategy;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * MapStruct mapper for converting between {@link com.acme.banking.core.model.Customer} domain objects and {@link com.acme.banking.infrastructure.persistence.CustomerJpaEntity} entities.
 *
 * <p>This interface provides bidirectional mapping:
 * <ul>
 *   <li>{@code toEntity()} - converts domain to JPA entity</li>
 *   <li>{@code toDomain()} - converts JPA entity to domain</li>
 * </ul>
 *
 * <p>MapStruct generates the implementation at compile time, ensuring type safety
 * and optimal performance without runtime reflection.
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:27:50.279600Z"
)
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED
)
public interface CustomerMapper {
    /**
     * Converts a domain object to a JPA entity.
     *
     * @param domain the domain object to convert
     * @return the corresponding JPA entity
     */
    CustomerJpaEntity toEntity(Customer domain);

    /**
     * Converts a JPA entity to a domain object using the {@code reconstitute()} factory method.
     *
     * @param entity the JPA entity to convert
     * @return the corresponding domain object, or null if entity is null
     */
    default Customer toDomain(CustomerJpaEntity entity) {
        if (entity == null) {
            return null;
        }
        return Customer.reconstitute(
                    map(entity.getId()),
                    entity.getFirstName(),
                    entity.getLastName(),
                    mapToEmail(entity.getEmail()),
                    entity.getPhone(),
                    toDomain(entity.getAddress()));
    }

    /**
     * Unwraps {@link com.acme.banking.core.model.CustomerId} to {@link java.lang.Long}.
     *
     * @param id the wrapped identity
     * @return the unwrapped value, or null if input is null
     */
    default Long map(CustomerId id) {
        return id != null ? id.value() : null;
    }

    /**
     * Wraps {@link java.lang.Long} into {@link com.acme.banking.core.model.CustomerId}.
     *
     * @param id the unwrapped value
     * @return the wrapped identity, or null if input is null
     */
    default CustomerId map(Long id) {
        return id != null ? new CustomerId(id) : null;
    }

    /**
     * Unwraps {@link Email} to {@link java.lang.String}.
     *
     * @param vo the Value Object to unwrap
     * @return the underlying value, or null if input is null
     */
    default String map(Email vo) {
        return vo != null ? vo.value() : null;
    }

    /**
     * Wraps {@link java.lang.String} into {@link Email}.
     *
     * @param value the primitive value to wrap
     * @return the Value Object, or null if input is null
     */
    default Email mapToEmail(String value) {
        return value != null ? new Email(value) : null;
    }

    /**
     * Converts {@link Money} domain object to {@link MoneyEmbeddable} JPA embeddable.
     *
     * @param domain the domain VALUE_OBJECT to convert
     * @return the corresponding JPA embeddable
     */
    MoneyEmbeddable toEmbeddable(Money domain);

    /**
     * Converts {@link MoneyEmbeddable} JPA embeddable to {@link Money} domain object.
     *
     * @param embeddable the JPA embeddable to convert
     * @return the corresponding domain VALUE_OBJECT
     */
    Money toDomain(MoneyEmbeddable embeddable);

    /**
     * Converts {@link Address} domain object to {@link AddressEmbeddable} JPA embeddable.
     *
     * @param domain the domain VALUE_OBJECT to convert
     * @return the corresponding JPA embeddable
     */
    AddressEmbeddable toEmbeddable(Address domain);

    /**
     * Converts {@link AddressEmbeddable} JPA embeddable to {@link Address} domain object.
     *
     * @param embeddable the JPA embeddable to convert
     * @return the corresponding domain VALUE_OBJECT
     */
    Address toDomain(AddressEmbeddable embeddable);
}
