package com.acme.banking.infrastructure.persistence;

import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link CustomerJpaEntity}.
 *
 * <p>This interface provides CRUD operations for CustomerJpaEntity entities.
 * Spring Data JPA automatically implements standard methods:
 * <ul>
 *   <li>{@code save(entity)}</li>
 *   <li>{@code findById(id)}</li>
 *   <li>{@code findAll()}</li>
 *   <li>{@code delete(entity)}</li>
 *   <li>{@code count()}</li>
 * </ul>
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:27:50.279081Z"
)
@Repository
public interface CustomerJpaRepository extends JpaRepository<CustomerJpaEntity, Long> {
    boolean existsByEmail(String email);

    Optional<CustomerJpaEntity> findByEmail(String email);

    Optional<CustomerJpaEntity> findById(Long id);
}
