package com.acme.banking.infrastructure.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.lang.String;
import java.math.BigDecimal;
import javax.annotation.processing.Generated;

@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:28:52.457606Z"
)
@Embeddable
public class MoneyEmbeddable {
    @Column(
            name = "amount"
    )
    private BigDecimal amount;

    @Column(
            name = "currency"
    )
    private String currency;

    public MoneyEmbeddable() {
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }
}
