package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.TransactionType;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.lang.Long;
import java.lang.String;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;

@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0",
        date = "2026-03-09T10:32:36.094661Z"
)
@Entity
@Table(
        name = "transactions"
)
public class TransactionJpaEntity {
    @Id
    @Column(
            name = "id",
            nullable = false
    )
    @GeneratedValue(
            strategy = GenerationType.IDENTITY
    )
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "type"
    )
    private TransactionType type;

    @Column(
            name = "description"
    )
    private String description;

    @Column(
            name = "reference"
    )
    private String reference;

    @Column(
            name = "account_id"
    )
    private Long accountId;

    @Column(
            name = "created_at"
    )
    private LocalDateTime createdAt;

    @Embedded
    private MoneyEmbeddable amount;

    public TransactionJpaEntity() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public TransactionType getType() {
        return type;
    }

    public void setType(TransactionType type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public MoneyEmbeddable getAmount() {
        return amount;
    }

    public void setAmount(MoneyEmbeddable amount) {
        this.amount = amount;
    }
}
