package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.TransferStatus;
import java.lang.Long;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link TransferJpaEntity}.
 *
 * <p>This interface provides CRUD operations for TransferJpaEntity entities.
 * Spring Data JPA automatically implements standard methods:
 * <ul>
 *   <li>{@code save(entity)}</li>
 *   <li>{@code findById(id)}</li>
 *   <li>{@code findAll()}</li>
 *   <li>{@code delete(entity)}</li>
 *   <li>{@code count()}</li>
 * </ul>
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:30:55.823812Z"
)
@Repository
public interface TransferJpaRepository extends JpaRepository<TransferJpaEntity, Long> {
    Optional<TransferJpaEntity> findById(Long id);

    List<TransferJpaEntity> findBySourceAccountId(Long sourceAccountId);

    List<TransferJpaEntity> findByStatus(TransferStatus status);

    List<TransferJpaEntity> findByTargetAccountId(Long targetAccountId);
}
