package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.Transfer;
import com.acme.banking.core.model.TransferId;
import com.acme.banking.core.model.TransferStatus;
import com.acme.banking.core.port.out.TransferRepository;
import java.lang.Override;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
        value = "io.hexaglue.plugin.jpa.JpaPlugin",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0",
        date = "2026-03-09T10:32:36.103567Z"
)
@Component
public class TransferRepositoryAdapter implements TransferRepository {
    private final TransferJpaRepository repository;

    private final TransferMapper mapper;

    public TransferRepositoryAdapter(TransferJpaRepository repository, TransferMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @Override
    public Optional<Transfer> findById(TransferId id) {
        return repository.findById(mapper.map(id)).map(mapper::toDomain);
    }

    @Override
    public List<Transfer> findBySourceAccountId(AccountId sourceAccountId) {
        return repository.findBySourceAccountId(sourceAccountId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public List<Transfer> findByStatus(TransferStatus status) {
        return repository.findByStatus(status).stream().map(mapper::toDomain).toList();
    }

    @Override
    public List<Transfer> findByTargetAccountId(AccountId targetAccountId) {
        return repository.findByTargetAccountId(targetAccountId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public Transfer save(Transfer transfer) {
        var entity = mapper.toEntity(transfer);
        var saved = repository.save(entity);
        return mapper.toDomain(saved);
    }
}
