package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.Address;
import com.acme.banking.core.model.Money;
import com.acme.banking.core.model.Transaction;
import com.acme.banking.core.model.TransactionId;
import java.lang.Long;
import javax.annotation.processing.Generated;
import org.mapstruct.CollectionMappingStrategy;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * MapStruct mapper for converting between {@link com.acme.banking.core.model.Transaction} domain objects and {@link com.acme.banking.infrastructure.persistence.TransactionJpaEntity} entities.
 *
 * <p>This interface provides bidirectional mapping:
 * <ul>
 *   <li>{@code toEntity()} - converts domain to JPA entity</li>
 *   <li>{@code toDomain()} - converts JPA entity to domain</li>
 * </ul>
 *
 * <p>MapStruct generates the implementation at compile time, ensuring type safety
 * and optimal performance without runtime reflection.
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-09T09:29:04.837381Z"
)
@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED
)
public interface TransactionMapper {
    /**
     * Converts a domain object to a JPA entity.
     *
     * @param domain the domain object to convert
     * @return the corresponding JPA entity
     */
    TransactionJpaEntity toEntity(Transaction domain);

    /**
     * Converts a JPA entity to a domain object using the {@code reconstitute()} factory method.
     *
     * @param entity the JPA entity to convert
     * @return the corresponding domain object, or null if entity is null
     */
    default Transaction toDomain(TransactionJpaEntity entity) {
        if (entity == null) {
            return null;
        }
        return Transaction.reconstitute(
                    map(entity.getId()),
                    mapToAccountId(entity.getAccountId()),
                    toDomain(entity.getAmount()),
                    entity.getType(),
                    entity.getDescription(),
                    entity.getReference(),
                    entity.getCreatedAt());
    }

    /**
     * Unwraps {@link com.acme.banking.core.model.TransactionId} to {@link java.lang.Long}.
     *
     * @param id the wrapped identity
     * @return the unwrapped value, or null if input is null
     */
    default Long map(TransactionId id) {
        return id != null ? id.value() : null;
    }

    /**
     * Wraps {@link java.lang.Long} into {@link com.acme.banking.core.model.TransactionId}.
     *
     * @param id the unwrapped value
     * @return the wrapped identity, or null if input is null
     */
    default TransactionId map(Long id) {
        return id != null ? new TransactionId(id) : null;
    }

    /**
     * Unwraps {@link AccountId} to {@link java.lang.Long}.
     *
     * @param vo the Value Object to unwrap
     * @return the underlying value, or null if input is null
     */
    default Long map(AccountId vo) {
        return vo != null ? vo.value() : null;
    }

    /**
     * Wraps {@link java.lang.Long} into {@link AccountId}.
     *
     * @param value the primitive value to wrap
     * @return the Value Object, or null if input is null
     */
    default AccountId mapToAccountId(Long value) {
        return value != null ? new AccountId(value) : null;
    }

    /**
     * Converts {@link Money} domain object to {@link MoneyEmbeddable} JPA embeddable.
     *
     * @param domain the domain VALUE_OBJECT to convert
     * @return the corresponding JPA embeddable
     */
    MoneyEmbeddable toEmbeddable(Money domain);

    /**
     * Converts {@link MoneyEmbeddable} JPA embeddable to {@link Money} domain object.
     *
     * @param embeddable the JPA embeddable to convert
     * @return the corresponding domain VALUE_OBJECT
     */
    Money toDomain(MoneyEmbeddable embeddable);

    /**
     * Converts {@link Address} domain object to {@link AddressEmbeddable} JPA embeddable.
     *
     * @param domain the domain VALUE_OBJECT to convert
     * @return the corresponding JPA embeddable
     */
    AddressEmbeddable toEmbeddable(Address domain);

    /**
     * Converts {@link AddressEmbeddable} JPA embeddable to {@link Address} domain object.
     *
     * @param embeddable the JPA embeddable to convert
     * @return the corresponding domain VALUE_OBJECT
     */
    Address toDomain(AddressEmbeddable embeddable);
}
