package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.TransactionType;
import java.lang.Long;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link TransactionJpaEntity}.
 *
 * <p>This interface provides CRUD operations for TransactionJpaEntity entities.
 * Spring Data JPA automatically implements standard methods:
 * <ul>
 *   <li>{@code save(entity)}</li>
 *   <li>{@code findById(id)}</li>
 *   <li>{@code findAll()}</li>
 *   <li>{@code delete(entity)}</li>
 *   <li>{@code count()}</li>
 * </ul>
 */
@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-05T14:47:09.268550Z"
)
@Repository
public interface TransactionJpaRepository extends JpaRepository<TransactionJpaEntity, Long> {
    List<TransactionJpaEntity> findByAccountId(Long accountId);

    List<TransactionJpaEntity> findByAccountIdAndType(Long accountId, TransactionType type);

    List<TransactionJpaEntity> findByAccountIdOrderByCreatedAtDesc(Long accountId);
}
