package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.AccountId;
import com.acme.banking.core.model.Transaction;
import com.acme.banking.core.model.TransactionType;
import com.acme.banking.core.port.out.TransactionRepository;
import java.lang.Override;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
        value = "io.hexaglue.plugin.jpa.JpaPlugin",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-05T14:47:09.276062Z"
)
@Component
public class TransactionRepositoryAdapter implements TransactionRepository {
    private final TransactionJpaRepository repository;

    private final TransactionMapper mapper;

    public TransactionRepositoryAdapter(TransactionJpaRepository repository,
            TransactionMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @Override
    public List<Transaction> findByAccountId(AccountId accountId) {
        return repository.findByAccountId(accountId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public List<Transaction> findByAccountIdAndType(AccountId accountId, TransactionType type) {
        return repository.findByAccountIdAndType(accountId.value(), type).stream().map(mapper::toDomain).toList();
    }

    @Override
    public List<Transaction> findByAccountIdOrderByCreatedAtDesc(AccountId accountId) {
        return repository.findByAccountIdOrderByCreatedAtDesc(accountId.value()).stream().map(mapper::toDomain).toList();
    }

    @Override
    public Transaction save(Transaction transaction) {
        var entity = mapper.toEntity(transaction);
        var saved = repository.save(entity);
        return mapper.toDomain(saved);
    }
}
