package com.acme.banking.infrastructure.persistence;

import com.acme.banking.core.model.TransferStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.lang.Long;
import java.lang.String;
import javax.annotation.processing.Generated;

@Generated(
        value = "io.hexaglue.plugin.jpa",
        comments = "Generated by HexaGlue JPA Plugin 3.1.0-SNAPSHOT",
        date = "2026-03-04T11:27:50.282510Z"
)
@Entity
@Table(
        name = "transfer"
)
public class TransferJpaEntity {
    @Id
    @Column(
            name = "id",
            nullable = false
    )
    private Long id;

    @Column(
            name = "source_account_id"
    )
    private Long sourceAccountId;

    @Column(
            name = "target_account_id"
    )
    private Long targetAccountId;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "status"
    )
    private TransferStatus status;

    @Column(
            name = "reason"
    )
    private String reason;

    @Embedded
    private MoneyEmbeddable amount;

    public TransferJpaEntity() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceAccountId() {
        return sourceAccountId;
    }

    public void setSourceAccountId(Long sourceAccountId) {
        this.sourceAccountId = sourceAccountId;
    }

    public Long getTargetAccountId() {
        return targetAccountId;
    }

    public void setTargetAccountId(Long targetAccountId) {
        this.targetAccountId = targetAccountId;
    }

    public TransferStatus getStatus() {
        return status;
    }

    public void setStatus(TransferStatus status) {
        this.status = status;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public MoneyEmbeddable getAmount() {
        return amount;
    }

    public void setAmount(MoneyEmbeddable amount) {
        this.amount = amount;
    }
}
